<a href="https://colab.research.google.com/github/LigiaTabaresTorres/Project_Mod2_TopGunLab/blob/main/EL_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
1

1

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1]

2

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0, 2]

3

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
arr[-1]

9

In [ ]:
arr[-3:]

array([7, 8, 9])

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])